//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationCRUD.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public int CId { get; set; }
        public string CName { get; set; }
        public int CId2 { get; set; }
    }
}
